# Generated by Django 2.1.11 on 2020-01-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200109_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
